# Generated by Django 4.1.2 on 2023-05-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_enckey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncKey',
        ),
    ]
